from fastapi import APIRouter, Depends, HTTPException, status, Body
from sqlalchemy.orm import Session
from database.connection import get_db
from models.alert import Alert
from models.incident import Incident
from models.activity_log import ActivityLog
from services.llm_service import LLMService
from services.threat_detection import KNOWN_MALICIOUS_IPS, KNOWN_MALICIOUS_HASHES
from routes.auth import get_optional_current_user
from datetime import datetime
from typing import List, Dict, Any

router = APIRouter(tags=["Threats"])

def map_alert_to_threat(alert: Alert) -> Dict[str, Any]:
    threat_id = alert.alert_id.replace("ALT-", "THR-")
    frontend_status = "Active" if alert.status in ["New", "Investigating"] else alert.status
    if frontend_status == "Resolved":
        frontend_status = "Resolved"

    return {
        "id": threat_id,
        "name": alert.title,
        "severity": alert.severity,
        "asset": alert.affected_asset or "Unknown Asset",
        "user": "alice.smith" if "workstation" in (alert.affected_asset or "").lower() else "system",
        "aiConfidence": int(alert.confidence_score * 100) if alert.confidence_score <= 1.0 else int(alert.confidence_score),
        "status": frontend_status,
        "firstSeen": alert.detected_at.isoformat() + "Z",
        "lastActivity": alert.created_at.isoformat() + "Z",
        "type": alert.category,
        "source": alert.source
    }

# ----------------- Backend REST Endpoints (/api/threats) -----------------

@router.get("/api/threats")
def read_api_threats(db: Session = Depends(get_db)):
    alerts = db.query(Alert).all()
    return [map_alert_to_threat(a) for a in alerts]

@router.get("/api/threats/{id}")
def read_api_threat(id: str, db: Session = Depends(get_db)):
    alert_id = id.replace("THR-", "ALT-")
    if alert_id.isdigit():
        alert = db.query(Alert).filter(Alert.id == int(alert_id)).first()
    else:
        alert = db.query(Alert).filter(Alert.alert_id == alert_id).first()

    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Threat indicator '{id}' not found."
        )

    threat = map_alert_to_threat(alert)
    llm = LLMService()
    analysis = llm.analyze_alert(alert.title, alert.category, alert.source_ip or "Unknown", alert.affected_asset or "Asset")

    threat["reasons"] = analysis.get("recommendations", ["Review firewall rules", "Isolate suspect endpoint"])
    threat["timeline"] = [
        {"time": alert.detected_at.strftime("%H:%M:%S"), "event": "Threat pattern observed"},
        {"time": alert.created_at.strftime("%H:%M:%S"), "event": f"Alert generated by {alert.source}"}
    ]
    threat["evidence"] = f"Correlation log message: {alert.description}\nSource IP: {alert.source_ip}\nDestination IP: {alert.destination_ip}"
    return threat

@router.post("/api/threats/check")
def check_indicator(payload: Dict[str, str] = Body(...)):
    """
    Checks if a given IP, domain, or file hash is listed in threat intelligence feeds.
    """
    indicator = payload.get("indicator")
    if not indicator:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Missing 'indicator' field in request body."
        )

    if indicator in KNOWN_MALICIOUS_IPS:
        return {
            "found": True,
            "type": "IP Address",
            "confidence": 0.95,
            "description": f"Known malicious IP. Context: {KNOWN_MALICIOUS_IPS[indicator]}",
            "source": "Aegis Threat Intel Feed"
        }

    if indicator in KNOWN_MALICIOUS_HASHES:
        return {
            "found": True,
            "type": "File Hash",
            "confidence": 0.98,
            "description": f"Known malicious signature. Threat: {KNOWN_MALICIOUS_HASHES[indicator]}",
            "source": "Aegis EDR Signature Feed"
        }

    return {
        "found": False,
        "message": f"Indicator '{indicator}' is not present in local threat intelligence feeds."
    }

@router.post("/api/threats/analyze")
def analyze_threat(payload: Dict[str, Any] = Body(...), db: Session = Depends(get_db)):
    """
    Provides AI explanations and suggestions for an alert.
    """
    alert_uuid = payload.get("alert_id")
    if not alert_uuid:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Missing 'alert_id' field in request body."
        )

    if isinstance(alert_uuid, int) or str(alert_uuid).isdigit():
        alert = db.query(Alert).filter(Alert.id == int(alert_uuid)).first()
    else:
        alert = db.query(Alert).filter(Alert.alert_id == alert_uuid).first()

    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with identifier '{alert_uuid}' not found."
        )

    llm = LLMService()
    analysis = llm.analyze_alert(
        alert_title=alert.title,
        category=alert.category,
        source_ip=alert.source_ip or "Unknown IP",
        affected_asset=alert.affected_asset or "Unknown Host"
    )

    log = ActivityLog(
        user_id="Analyst",
        action="THREAT_ANALYZED",
        description=f"Requested AI analysis for alert {alert.alert_id}.",
        timestamp=datetime.utcnow()
    )
    db.add(log)
    db.commit()

    return analysis

# ----------------- Frontend Compatibility Endpoints -----------------

@router.get("/threats")
def get_frontend_threats(db: Session = Depends(get_db)):
    return read_api_threats(db)

@router.get("/threats/{id}")
def get_frontend_threat(id: str, db: Session = Depends(get_db)):
    return read_api_threat(id, db)

@router.get("/attack-graph")
def get_frontend_attack_graph(db: Session = Depends(get_db)):
    active_incidents = db.query(Incident).filter(Incident.status.in_(["Open", "Investigating"])).all()

    nodes = [
        {"id": "fw-01", "label": "Perimeter Firewall", "type": "firewall", "x": 150, "y": 100, "critical": False},
        {"id": "workstation-04", "label": "WORKSTATION-04", "type": "endpoint", "x": 300, "y": 200, "critical": False},
        {"id": "db-prod", "label": "Prod Customer DB", "type": "database", "x": 600, "y": 250, "critical": True},
        {"id": "cloud-api", "label": "Cloud API Gateway", "type": "cloud", "x": 450, "y": 120, "critical": False}
    ]
    edges = [
        {"from": "fw-01", "to": "workstation-04", "severity": "Medium"},
        {"from": "workstation-04", "to": "db-prod", "severity": "High"}
    ]

    for inc in active_incidents:
        if inc.attacker:
            attacker_id = f"attacker-{inc.incident_id}"
            nodes.append({
                "id": attacker_id,
                "label": f"Attacker ({inc.attacker})",
                "type": "attacker",
                "x": 50,
                "y": 250,
                "critical": True
            })
            edges.append({
                "from": attacker_id,
                "to": "fw-01",
                "severity": inc.severity
            })

    return {
        "nodes": nodes,
        "edges": edges
    }
